"""add role column

Revision ID: 044cf05e02b0
Revises: eafac297c779
Create Date: 2026-04-14 13:11:41.402076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044cf05e02b0'
down_revision: Union[str, Sequence[str], None] = 'eafac297c779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('test_col', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
