"""add role to users

Revision ID: eafac297c779
Revises: 22132b91b374
Create Date: 2026-04-14 00:45:36.258684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafac297c779'
down_revision: Union[str, Sequence[str], None] = '22132b91b374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('test_col', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
